<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE people [
    <!ELEMENT people (person+)>
    <!ELEMENT person (namae,tanjobi)>
    <!ELEMENT namae (#PCDATA)>
    <!ELEMENT tanjobi (#PCDATA)>
]>

<people>
    <person>
    	<namae>伊藤博文</namae>
    	<tanjobi>1841/10/16</tanjobi>
    </person>
    <person>
    	<namae>黒田清隆</namae>
    	<tanjobi>1840/11/9</tanjobi>
    </person>
    <person>
    	<namae>三条実美</namae>
    	<tanjobi>1837/3/13</tanjobi>
    </person>
    <person>
    	<namae>山県有朋</namae>
    	<tanjobi>1838/6/14</tanjobi>
    </person>
    <person>
    	<namae>松方正義</namae>
    	<tanjobi>1835/3/23</tanjobi>
    </person>
    <person>
    	<namae>大隈重信</namae>
    	<tanjobi>1838/3/11</tanjobi>
    </person>
    <person>
    	<namae>西園寺公望</namae>
    	<tanjobi>1849/12/6</tanjobi>
    </person>
    <person>
    	<namae>桂太郎</namae>
    	<tanjobi>1848/1/4</tanjobi>
    </person>
    <person>
    	<namae>山本権兵衛</namae>
    	<tanjobi>1852/11/26</tanjobi>
    </person>
    <person>
    	<namae>寺内正毅</namae>
    	<tanjobi>1852/2/24</tanjobi>
    </person>
    <person>
    	<namae>原敬</namae>
    	<tanjobi>1856/3/15</tanjobi>
    </person>
    <person>
    	<namae>高橋是清</namae>
    	<tanjobi>1854/9/19</tanjobi>
    </person>
    <person>
    	<namae>加藤友三郎</namae>
    	<tanjobi>1861/4/1</tanjobi>
    </person>
    <person>
    	<namae>清浦奎吾</namae>
    	<tanjobi>1850/3/27</tanjobi>
    </person>
    <person>
    	<namae>加藤高明</namae>
    	<tanjobi>1860/1/25</tanjobi>
    </person>
    <person>
    	<namae>若槻禮次郎</namae>
    	<tanjobi>1866/3/21</tanjobi>
    </person>
    <person>
    	<namae>田中義一</namae>
    	<tanjobi>1864/7/25</tanjobi>
    </person>
    <person>
    	<namae>濱口雄幸</namae>
    	<tanjobi>1870/5/1</tanjobi>
    </person>
    <person>
    	<namae>犬養毅</namae>
    	<tanjobi>1855/6/4</tanjobi>
    </person>
    <person>
    	<namae>斎藤実</namae>
    	<tanjobi>1858/12/2</tanjobi>
    </person>
    <person>
    	<namae>岡田啓介</namae>
    	<tanjobi>1868/2/14</tanjobi>
    </person>
    <person>
    	<namae>広田弘毅</namae>
    	<tanjobi>1878/2/14</tanjobi>
    </person>
    <person>
    	<namae>林銑十郎</namae>
    	<tanjobi>1876/2/23</tanjobi>
    </person>
    <person>
    	<namae>近衛文麿</namae>
    	<tanjobi>1891/10/12</tanjobi>
    </person>
    <person>
    	<namae>平沼騏一郎</namae>
    	<tanjobi>1867/10/25</tanjobi>
    </person>
    <person>
    	<namae>阿部信行</namae>
    	<tanjobi>1875/11/24</tanjobi>
    </person>
    <person>
    	<namae>米内光政</namae>
    	<tanjobi>1880/3/2</tanjobi>
    </person>
    <person>
    	<namae>東條英機</namae>
    	<tanjobi>1884/7/30</tanjobi>
    </person>
    <person>
    	<namae>小磯國昭</namae>
    	<tanjobi>1880/3/22</tanjobi>
    </person>
    <person>
    	<namae>鈴木貫太郎</namae>
    	<tanjobi>1868/1/18</tanjobi>
    </person>
    <person>
    	<namae>東久邇宮稔彦王</namae>
    	<tanjobi>1887/12/3</tanjobi>
    </person>
    <person>
    	<namae>幣原喜重郎</namae>
    	<tanjobi>1872/9/13</tanjobi>
    </person>
    <person>
    	<namae>吉田茂</namae>
    	<tanjobi>1878/9/22</tanjobi>
    </person>
    <person>
    	<namae>片山哲</namae>
    	<tanjobi>1887/7/28</tanjobi>
    </person>
    <person>
    	<namae>芦田均</namae>
    	<tanjobi>1887/11/15</tanjobi>
    </person>
    <person>
    	<namae>鳩山一郎</namae>
    	<tanjobi>1883/1/1</tanjobi>
    </person>
    <person>
    	<namae>石橋湛山</namae>
    	<tanjobi>1884/9/25</tanjobi>
    </person>
    <person>
    	<namae>岸信介</namae>
    	<tanjobi>1896/11/13</tanjobi>
    </person>
    <person>
    	<namae>池田勇人</namae>
    	<tanjobi>1899/12/3</tanjobi>
    </person>
    <person>
    	<namae>佐藤栄作</namae>
    	<tanjobi>1901/3/27</tanjobi>
    </person>
    <person>
    	<namae>田中角栄</namae>
    	<tanjobi>1918/5/4</tanjobi>
    </person>
    <person>
    	<namae>三木武夫</namae>
    	<tanjobi>1907/3/17</tanjobi>
    </person>
    <person>
    	<namae>福田赳夫</namae>
    	<tanjobi>1905/1/14</tanjobi>
    </person>
    <person>
    	<namae>大平正芳</namae>
    	<tanjobi>1910/3/12</tanjobi>
    </person>
    <person>
    	<namae>鈴木善幸</namae>
    	<tanjobi>1911/1/11</tanjobi>
    </person>
    <person>
    	<namae>中曽根康弘</namae>
    	<tanjobi>1918/5/27</tanjobi>
    </person>
    <person>
    	<namae>竹下登</namae>
    	<tanjobi>1924/2/26</tanjobi>
    </person>
    <person>
    	<namae>宇野宗佑</namae>
    	<tanjobi>1922/8/27</tanjobi>
    </person>
    <person>
    	<namae>海部俊樹</namae>
    	<tanjobi>1931/1/2</tanjobi>
    </person>
    <person>
    	<namae>宮澤喜一</namae>
    	<tanjobi>1919/10/8</tanjobi>
    </person>
    <person>
    	<namae>細川護熙</namae>
    	<tanjobi>1938/1/14</tanjobi>
    </person>
    <person>
    	<namae>羽田孜</namae>
    	<tanjobi>1935/8/24</tanjobi>
    </person>
    <person>
    	<namae>村山富市</namae>
    	<tanjobi>1924/3/3</tanjobi>
    </person>
    <person>
    	<namae>橋本龍太郎</namae>
    	<tanjobi>1937/7/29</tanjobi>
    </person>
    <person>
    	<namae>小渕恵三</namae>
    	<tanjobi>1937/6/25</tanjobi>
    </person>
    <person>
    	<namae>森喜朗</namae>
    	<tanjobi>1937/7/14</tanjobi>
    </person>
    <person>
    	<namae>小泉純一郎</namae>
    	<tanjobi>1942/1/8</tanjobi>
    </person>
    <person>
    	<namae>安倍晋三</namae>
    	<tanjobi>1954/9/21</tanjobi>
    </person>
    <person>
    	<namae>福田康夫</namae>
    	<tanjobi>1936/7/16</tanjobi>
    </person>
    <person>
    	<namae>麻生太郎</namae>
    	<tanjobi>1940/9/20</tanjobi>
    </person>
    <person>
    	<namae>鳩山由紀夫</namae>
    	<tanjobi>1947/2/11</tanjobi>
    </person>
    <person>
    	<namae>菅直人</namae>
    	<tanjobi>1946/10/10</tanjobi>
    </person>
    <person>
    	<namae>野田佳彦</namae>
        <tanjobi>1957/5/20</tanjobi>
    </person>
</people>